### ISSUE TITLE
Temporal chains not being removed automatically while 'Use Flask to Remove Curses' is checked.

### ISSUE THREAD

**Issue by fakeaccount1234** [badplayerr/beta-autopot#1]
As per title, the curse Temporal Chains isn't being removed automatically.

**Comment by badplayerr** [comment]
Seems to be removing it on my end. As seen [here.](http://b.1339.cf/drwkuxu.webm)

**Comment by fakeaccount1234** [comment]
Upon further testing it seems to remove some instances of Temporal Chains but not others. It will remove the curse if applied by a Chronophage rare. I'll try and get some videos up.

**Comment by badplayerr** [comment]
It is a duration issue, the mortality experimenters in lunaris and hexfront mobs both seem to apply a 2 second temp chains which wouldn't have been removed the way I 'fixed' it before.

Should be good now. Should have done it this way in the first place.
It should remove curses, regardless of duration, but won't try to remove curses applied by maps.
https://github.com/badplayerr/beta-autopot/releases/download/2.0.4b/autopot.exe
Try that and let me know if it fixed it.

**Comment by fakeaccount1234** [comment]
This has fixed the problem. Thanks again.
