### ISSUE TITLE
RemoveCorruptedBloodCharges don't work

### ISSUE THREAD

**Issue by yuwei111** [badplayerr/beta-autopot#5]
Maybe the Buffcharge's offset is charged.
In debug window, the corrupted_blood & corrupted_blood_rain buff Charges always show 0.

Remove Corrupted Blood doesn't work anymore.
because (BuffCharges>=RemoveCorruptedBloodCharges) always false

**Comment by badplayerr** [comment]
Updated the offset, should work now.
