### ISSUE TITLE
patch 2.1.2d ruined your autopot

### ISSUE THREAD

**Issue by poopGOD** [badplayerr/beta-autopot#6]
it now crashes after a few seconds

aobscan fail: pattern not found

baseMgrPtr not found with AoBScan, script will now terminate

**Comment by Soruja** [comment]
can say same thing happens to me.

**Comment by CodeLover19** [comment]
does everything else work besides auto pot what about auto quick at %hp

**Comment by Soruja** [comment]
as of right now none of the pot works for me...
